- hosts: webserver
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root

  vars:
     repo_url: https://github.com/Monali-Panchal/AnsibleProject.git
     repo_dest: /home/ubuntu/repos/
     build_path: /home/ubuntu/repos
     destination_path: /var/www/html/index.html
     src_build_path: /home/ubuntu/repos/build/index.html

  tasks:
    - name: Clone a github repository
      git:
        repo: "{{repo_url}}"
        dest: "{{repo_dest}}"
        version: master
        clone: yes
        update: yes

    - name: Install the Required packages
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - npm
    - name: Install dependencies
      npm:
        path: "{{build_path}}"
    - name: Build application
      command: npm run build
      args:
        chdir: "{{build_path}}"

    - name: copying the index.html to remote Server
      copy:
        src: "{{src_build_path}}"
        dest: "{{destination_path}}"
        remote_src: yes
        owner: root
        group: root
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
