- hosts: webserver
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root

  tasks:
   - name: install apache on remote server
     apt:
       name: apache2
       state: latest
       update_cache: yes
   - name: enable the service
     service:
       enabled: true
       name: apache2
       state: started
   - name: copying the index.html to remote Server
     copy:
       src: /etc/ansible/index_files/index.html
       dest: /var/www/html/index.html
     notify: Restart Apache

  handlers:
   - name: Restart Apache
     service:
       name: apache2
       state: restarted
