- hosts: webserver
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/Monali-Panchal/AnsibleProject.git
        dest: /home/debian/repos/
        version: master
        clone: yes
        update: yes

    - name: Install the Required packages
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - npm

    - name: Install dependencies
      npm:
        path: /home/ubuntu/repos

    - name: Build app
      command: npm run build
      args:
        chdir: /home/ubuntu/repos

    - name: copying the index.html to remote Server
      copy:
        src: /home/ubuntu/repos/build/index.html
        dest: /var/www/html/index.html
        remote_src: yes
        owner: root
        group: root
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
