repo_url: https://github.com/harshm1225/create-react-app.git
destination_path: /var/www/html/index.html
repo_dest: /home/ec2-user/repos/
build_path: /home/ec2-user/repos
src_build_path: ~/reactjs-demo/build/index.html
