    - name: Install the Required packages - RedHat
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - httpd
        - git

    - name: Clone a github repository - RedHat
      git:
        repo: "{{repo_url}}"
        dest: "{{repo_dest}}"
        force: yes
        version: master
        clone: yes
        update: yes

    - name: update npm global packages
      npm:
        name: '{{ item }}'
        global: yes
        version: '6.14.13'
      with_items: '{{ npm_packages }}'
      tags:
        - always

    - name: Install dependencies and building
      ansible.builtin.shell: |
        npm install
        npm run build
      args:
        chdir: "{{build_path}}"

    - name: copying the index.html to remote Server -RedHat
      copy:
        src: "{{src_build_path}}"
        dest: "{{destination_path}}"
        remote_src: yes
        owner: root
        group: root
      notify: Restart Apache
