    - name: Install the Required packages - RedHat
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - httpd
        - git
        - python3
        - nodejs

    - name: Clone a github repository - RedHat
      git:
        repo: "{{repo_url}}"
        dest: ~/reactjs-demo
        force: yes
        version: master
        clone: yes
        update: yes

    # Install project dependencies with npm
    - name: Install project dependencies with npm
      command: /usr/bin/npm install
      args:
        chdir: ~/reactjs-demo

    # Run npm build on RedHat
    - name: Run npm build on RedHat
      command: /usr/bin/npm run build
      args:
        chdir: ~/reactjs-demo
      ignore_errors: true


    - name: copying the index.html to remote Server -RedHat
      copy:
        src: "{{src_build_path}}"
        dest: "{{destination_path}}"
        remote_src: yes
        owner: root
        group: root
      notify: Restart Apache

    # Set file permissions for Apache on RedHat
    - name: Set file permissions for Apache on RedHat
      file:
        path: /var/www/html
        owner: apache
        group: apache
        mode: "0755"
