    - name: Clone a github repository
      git:
        repo: "{{repo_url}}"
        dest: "{{repo_dest}}"
        force: yes
        version: master
        clone: yes
        update: yes

    - name: Install the Required packages
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - npm
        - git
    - name: Install dependencies
      npm:
        path: "{{build_path}}"
    - name: Build application
      command: npm run build
      args:
        chdir: "{{build_path}}"

    - name: copying the index.html to remote Server
      copy:
        src: "{{src_build_path}}"
        dest: "{{destination_path}}"
        remote_src: yes
        owner: root
        group: root
      notify: Restart Apache
