    - name: Install the Required packages - RedHat
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - httpd
        - git
        - python3
        - nodejs

    - name: Clone a github repository - RedHat
      git:
        repo: "{{repo_url}}"
        dest: "{{repo_dest}}"
        force: yes
        version: master
        clone: yes
        update: yes

    - name: Install npm on RedHat remote machine
      yum:
        name: npm
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: Install dependencies using npm
      command: /usr/bin/npm install
      args:
        chdir: "{{build_path}}"
      environment:
        HOME: /root

    - name: Run npm build
      command: /usr/bin/npm run build
      args:
        chdir: "{{build_path}}"
      environment:
        HOME: /root

    - name: copying the index.html to remote Server -RedHat
      copy:
        src: "{{src_build_path}}"
        dest: "{{destination_path}}"
        remote_src: yes
        owner: root
        group: root
      notify: Restart Apache
