    - name: Install the Required packages - RedHat
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - httpd
        - git
        - python3
        - nodejs

    - name: Clone a github repository - RedHat
      git:
        repo: "{{repo_url}}"
        dest: ~/reactjs-demo
        force: yes
        version: master
        clone: yes
        update: yes

    - name: Install Node.js 16.x.x
      yum:
        name: nodejs
        state: present
        enablerepo: nodesource
        update_cache: yes

    - name: Install npm with specific version
      npm:
        name: npm
        global: yes
        version: "8.5.1"

    - name: Install dependencies using npm
      command: npm install
      args:
        chdir: ~/reactjs-demo
      environment:
        HOME: /root

    - name: Run npm build
      command: npm run build
      args:
        chdir: ~/reactjs-demo
      environment:
        HOME: /root

    - name: copying the index.html to remote Server -RedHat
      copy:
        src: "{{src_build_path}}"
        dest: "{{destination_path}}"
        remote_src: yes
        owner: root
        group: root
      notify: Restart Apache
